<?php

return [
    'catalog' => [
        [
            'title' => 'Lunar Horizon',
            'year' => 2025,
            'genres' => ['Sci-Fi', 'Thriller'],
            'overview' => 'A lone engineer uncovers an impossible signal from the dark side of the moon and risks everything to follow it.',
            'rating' => 8.3,
            'runtime' => 128,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Lunar+Horizon',
        ],
        [
            'title' => 'Neon Alley',
            'year' => 2024,
            'genres' => ['Action', 'Crime'],
            'overview' => 'In a city where neon lights never fade, an ex-detective returns to stop a syndicate fueled by synthetic dreams.',
            'rating' => 7.7,
            'runtime' => 116,
            'poster' => 'https://dummyimage.com/500x750/111827/ffffff&text=Neon+Alley',
        ],
        [
            'title' => 'Atlas Garden',
            'year' => 2023,
            'genres' => ['Drama', 'Mystery'],
            'overview' => 'An archivist discovers a map that reveals a garden capable of bending time and the fragile memories of those who enter.',
            'rating' => 8.0,
            'runtime' => 124,
            'poster' => 'https://dummyimage.com/500x750/0f172a/ffffff&text=Atlas+Garden',
        ],
        [
            'title' => 'Harbor of Echoes',
            'year' => 2022,
            'genres' => ['Romance', 'Fantasy'],
            'overview' => 'Two strangers hear each other\'s thoughts when they cross paths at a foggy coastal town built atop forgotten ruins.',
            'rating' => 7.4,
            'runtime' => 109,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Harbor+of+Echoes',
        ],
        [
            'title' => 'Glasswork',
            'year' => 2024,
            'genres' => ['Thriller'],
            'overview' => 'A forensic sculptor must reconstruct the final moments of a missing tech mogul using fragments of shattered AI memories.',
            'rating' => 7.9,
            'runtime' => 121,
            'poster' => 'https://dummyimage.com/500x750/0b1120/ffffff&text=Glasswork',
        ],
        [
            'title' => 'Aurora Diaries',
            'year' => 2021,
            'genres' => ['Adventure', 'Family'],
            'overview' => 'Three siblings follow their late mother\'s journal to chase auroras that supposedly unlock hidden worlds.',
            'rating' => 7.1,
            'runtime' => 103,
            'poster' => 'https://dummyimage.com/500x750/1e293b/ffffff&text=Aurora+Diaries',
        ],
        [
            'title' => 'Iron Seasons',
            'year' => 2020,
            'genres' => ['Historical', 'Drama'],
            'overview' => 'A botanist in the industrial revolution fights to preserve plant life as factories spread across her homeland.',
            'rating' => 8.1,
            'runtime' => 134,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Iron+Seasons',
        ],
        [
            'title' => 'Signal Fire',
            'year' => 2023,
            'genres' => ['War', 'Drama'],
            'overview' => 'Trapped behind enemy lines, a radio operator becomes the voice for a resistance she never meant to lead.',
            'rating' => 7.5,
            'runtime' => 118,
            'poster' => 'https://dummyimage.com/500x750/0f172a/ffffff&text=Signal+Fire',
        ],
        [
            'title' => 'Orbital Hearts',
            'year' => 2024,
            'genres' => ['Sci-Fi', 'Romance'],
            'overview' => 'Two astronauts on rival missions fall in love while stranded aboard a derelict observatory.',
            'rating' => 7.8,
            'runtime' => 110,
            'poster' => 'https://dummyimage.com/500x750/020617/ffffff&text=Orbital+Hearts',
        ],
        [
            'title' => 'Solar Tide',
            'year' => 2019,
            'genres' => ['Documentary'],
            'overview' => 'A sweeping documentary about communities rebuilding coastlines using solar-powered tidal walls.',
            'rating' => 7.3,
            'runtime' => 96,
            'poster' => 'https://dummyimage.com/500x750/1e293b/ffffff&text=Solar+Tide',
        ],
        [
            'title' => 'The Far Wild',
            'year' => 2025,
            'genres' => ['Adventure'],
            'overview' => 'An explorer charts an unrecorded rainforest only to discover the trees speak a forgotten dialect.',
            'rating' => 7.6,
            'runtime' => 115,
            'poster' => 'https://dummyimage.com/500x750/111827/ffffff&text=The+Far+Wild',
        ],
        [
            'title' => 'Celestial Relay',
            'year' => 2023,
            'genres' => ['Sci-Fi'],
            'overview' => 'A team of scientists must repair an orbital relay to stop a cascading blackout across colonies.',
            'rating' => 7.2,
            'runtime' => 112,
            'poster' => 'https://dummyimage.com/500x750/020617/ffffff&text=Celestial+Relay',
        ],
        [
            'title' => 'Whisperwood',
            'year' => 2021,
            'genres' => ['Fantasy'],
            'overview' => 'A teenager inherits a forest that whispers secrets about the people who enter.',
            'rating' => 7.0,
            'runtime' => 101,
            'poster' => 'https://dummyimage.com/500x750/0f172a/ffffff&text=Whisperwood',
        ],
        [
            'title' => 'Crimson Atlas',
            'year' => 2022,
            'genres' => ['Action'],
            'overview' => 'A courier must deliver a map that exposes the empire\'s hidden prisons before it falls into the wrong hands.',
            'rating' => 7.4,
            'runtime' => 107,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Crimson+Atlas',
        ],
        [
            'title' => 'Mirror Signal',
            'year' => 2024,
            'genres' => ['Mystery', 'Thriller'],
            'overview' => 'A linguist decodes reflections in surveillance footage to unveil a buried conspiracy.',
            'rating' => 7.9,
            'runtime' => 119,
            'poster' => 'https://dummyimage.com/500x750/020617/ffffff&text=Mirror+Signal',
        ],
        [
            'title' => 'Azure Quay',
            'year' => 2018,
            'genres' => ['Drama'],
            'overview' => 'A fishing town confronts its past when an artist paints murals predicting the tides.',
            'rating' => 7.2,
            'runtime' => 104,
            'poster' => 'https://dummyimage.com/500x750/1e293b/ffffff&text=Azure+Quay',
        ],
        [
            'title' => 'Silent Helix',
            'year' => 2025,
            'genres' => ['Sci-Fi', 'Horror'],
            'overview' => 'Geneticists resurrect an ancient seed that infects their research station with eerie harmonics.',
            'rating' => 7.6,
            'runtime' => 108,
            'poster' => 'https://dummyimage.com/500x750/111827/ffffff&text=Silent+Helix',
        ],
        [
            'title' => 'Deep Current',
            'year' => 2020,
            'genres' => ['Thriller'],
            'overview' => 'Divers investigating a sunken lab find an AI that predicts disasters hours before they happen.',
            'rating' => 7.5,
            'runtime' => 113,
            'poster' => 'https://dummyimage.com/500x750/0b1120/ffffff&text=Deep+Current',
        ],
        [
            'title' => 'Violet North',
            'year' => 2021,
            'genres' => ['Drama'],
            'overview' => 'A music producer returns to her arctic hometown to stage a concert under the midnight sun.',
            'rating' => 7.1,
            'runtime' => 105,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Violet+North',
        ],
        [
            'title' => 'Circuit Skies',
            'year' => 2022,
            'genres' => ['Animation', 'Family'],
            'overview' => 'A young inventor builds gliders that teach kids to repair a polluted atmosphere.',
            'rating' => 7.3,
            'runtime' => 95,
            'poster' => 'https://dummyimage.com/500x750/0f172a/ffffff&text=Circuit+Skies',
        ],
        [
            'title' => 'Marrowlight',
            'year' => 2023,
            'genres' => ['Horror'],
            'overview' => 'Residents of a mining town awaken glowing bones that reveal how each villager will die.',
            'rating' => 7.4,
            'runtime' => 111,
            'poster' => 'https://dummyimage.com/500x750/0b1120/ffffff&text=Marrowlight',
        ],
        [
            'title' => 'Cloudglass',
            'year' => 2019,
            'genres' => ['Fantasy', 'Romance'],
            'overview' => 'A glassblower crafts windows that let people visit their happiest memories for one last farewell.',
            'rating' => 7.8,
            'runtime' => 117,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Cloudglass',
        ],
        [
            'title' => 'Quantum Relay',
            'year' => 2020,
            'genres' => ['Sci-Fi'],
            'overview' => 'A courier teleports through quantum gates that malfunction when corporate sabotage strikes.',
            'rating' => 7.2,
            'runtime' => 102,
            'poster' => 'https://dummyimage.com/500x750/020617/ffffff&text=Quantum+Relay',
        ],
        [
            'title' => 'Gilded Static',
            'year' => 2024,
            'genres' => ['Drama', 'Music'],
            'overview' => 'A faded rockstar records in an abandoned theater where every note conjures fragments of their past shows.',
            'rating' => 7.7,
            'runtime' => 119,
            'poster' => 'https://dummyimage.com/500x750/1e293b/ffffff&text=Gilded+Static',
        ],
        [
            'title' => 'Fable Circuit',
            'year' => 2025,
            'genres' => ['Animation'],
            'overview' => 'Animated folklore collides with future tech when children hack into a mythological archive.',
            'rating' => 7.5,
            'runtime' => 97,
            'poster' => 'https://dummyimage.com/500x750/111827/ffffff&text=Fable+Circuit',
        ],
        [
            'title' => 'Last Meridian',
            'year' => 2018,
            'genres' => ['Adventure', 'Drama'],
            'overview' => 'Sailors chase the final sunset line to prevent an endless night from freezing their world.',
            'rating' => 7.0,
            'runtime' => 122,
            'poster' => 'https://dummyimage.com/500x750/0f172a/ffffff&text=Last+Meridian',
        ],
        [
            'title' => 'Eclipse Harbor',
            'year' => 2021,
            'genres' => ['Mystery'],
            'overview' => 'An amateur astronomer investigates why their harbor experiences eclipses that no one else sees.',
            'rating' => 7.3,
            'runtime' => 108,
            'poster' => 'https://dummyimage.com/500x750/0b1120/ffffff&text=Eclipse+Harbor',
        ],
        [
            'title' => 'Chrome Valley',
            'year' => 2022,
            'genres' => ['Action', 'Sci-Fi'],
            'overview' => 'Street racers compete with solar-powered vehicles in a desert metropolis to win their freedom.',
            'rating' => 7.6,
            'runtime' => 114,
            'poster' => 'https://dummyimage.com/500x750/111827/ffffff&text=Chrome+Valley',
        ],
        [
            'title' => 'Midnight Ledger',
            'year' => 2023,
            'genres' => ['Crime', 'Thriller'],
            'overview' => 'An accountant hacks a crime ledger to expose a network of laundering art galleries.',
            'rating' => 7.8,
            'runtime' => 118,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Midnight+Ledger',
        ],
        [
            'title' => 'Opal Drift',
            'year' => 2020,
            'genres' => ['Drama', 'Sci-Fi'],
            'overview' => 'Miners on an asteroid colony stage a heist to steal the mineral that keeps them imprisoned.',
            'rating' => 7.4,
            'runtime' => 111,
            'poster' => 'https://dummyimage.com/500x750/020617/ffffff&text=Opal+Drift',
        ],
        [
            'title' => 'The Quiet Array',
            'year' => 2019,
            'genres' => ['Mystery', 'Drama'],
            'overview' => 'A sound engineer notices cosmic interference that reveals a hidden colony in the ocean.',
            'rating' => 7.2,
            'runtime' => 106,
            'poster' => 'https://dummyimage.com/500x750/111827/ffffff&text=The+Quiet+Array',
        ],
        [
            'title' => 'Echo Rift',
            'year' => 2024,
            'genres' => ['Sci-Fi'],
            'overview' => 'A physicist steps through a rift where every decision echoes back as ghostly projections.',
            'rating' => 8.0,
            'runtime' => 123,
            'poster' => 'https://dummyimage.com/500x750/020617/ffffff&text=Echo+Rift',
        ],
        [
            'title' => 'Paper Nebula',
            'year' => 2021,
            'genres' => ['Animation', 'Adventure'],
            'overview' => 'Stop-motion explorers fold constellations into origami ships to rescue their missing captain.',
            'rating' => 7.5,
            'runtime' => 99,
            'poster' => 'https://dummyimage.com/500x750/1e293b/ffffff&text=Paper+Nebula',
        ],
        [
            'title' => 'Skyline Memoir',
            'year' => 2019,
            'genres' => ['Drama'],
            'overview' => 'A photographer builds a living museum in skyscraper rooftops to preserve fading neighborhoods.',
            'rating' => 7.1,
            'runtime' => 118,
            'poster' => 'https://dummyimage.com/500x750/0f172a/ffffff&text=Skyline+Memoir',
        ],
        [
            'title' => 'Frosted Signals',
            'year' => 2020,
            'genres' => ['Thriller'],
            'overview' => 'A communications team stationed in Antarctica decodes distress calls from a parallel research base.',
            'rating' => 7.6,
            'runtime' => 110,
            'poster' => 'https://dummyimage.com/500x750/0b1120/ffffff&text=Frosted+Signals',
        ],
        [
            'title' => 'Glimmerfall',
            'year' => 2022,
            'genres' => ['Fantasy'],
            'overview' => 'A cartographer charts waterfalls that glow with glyphs describing other universes.',
            'rating' => 7.8,
            'runtime' => 120,
            'poster' => 'https://dummyimage.com/500x750/1f2937/ffffff&text=Glimmerfall',
        ],
        [
            'title' => 'Tangent City',
            'year' => 2023,
            'genres' => ['Sci-Fi', 'Comedy'],
            'overview' => 'Mathematicians battle bureaucracy when their perfectly calculated transit system gains sentience.',
            'rating' => 7.3,
            'runtime' => 102,
            'poster' => 'https://dummyimage.com/500x750/0f172a/ffffff&text=Tangent+City',
        ],
        [
            'title' => 'Velvet Relay',
            'year' => 2018,
            'genres' => ['Drama', 'Mystery'],
            'overview' => 'A courier inherits velvet letters that reveal an underground network of artists smuggling dissident plays.',
            'rating' => 7.2,
            'runtime' => 108,
            'poster' => 'https://dummyimage.com/500x750/1e293b/ffffff&text=Velvet+Relay',
        ],
    ],
];
