<?php

namespace Tests\Feature\Database;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use PHPUnit\Framework\Attributes\DataProvider;
use Tests\TestCase;

class MigrationsTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @param  list<string>  $expectedColumns
     */
    #[DataProvider('tableColumnsProvider')]
    public function test_migrations_create_expected_schema(string $table, array $expectedColumns): void
    {
        $this->assertTrue(
            Schema::hasTable($table),
            sprintf('Failed asserting that the %s table exists.', $table),
        );

        foreach ($expectedColumns as $column) {
            $this->assertTrue(
                Schema::hasColumn($table, $column),
                sprintf('Failed asserting that %s has the %s column.', $table, $column),
            );
        }
    }

    /**
     * @return array<string, array{0: string, 1: list<string>}
     */
    public static function tableColumnsProvider(): array
    {
        return [
            'users table' => ['users', [
                'id',
                'name',
                'email',
                'email_verified_at',
                'password',
                'preferred_locale',
                'role',
                'remember_token',
                'stripe_id',
                'pm_type',
                'pm_last_four',
                'trial_ends_at',
                'created_at',
                'updated_at',
            ]],
            'password reset tokens table' => ['password_reset_tokens', [
                'email',
                'token',
                'created_at',
            ]],
            'sessions table' => ['sessions', [
                'id',
                'user_id',
                'ip_address',
                'user_agent',
                'payload',
                'last_activity',
            ]],
            'cache table' => ['cache', [
                'key',
                'value',
                'expiration',
            ]],
            'cache locks table' => ['cache_locks', [
                'key',
                'owner',
                'expiration',
            ]],
            'jobs table' => ['jobs', [
                'id',
                'queue',
                'payload',
                'attempts',
                'reserved_at',
                'available_at',
                'created_at',
            ]],
            'job batches table' => ['job_batches', [
                'id',
                'name',
                'total_jobs',
                'pending_jobs',
                'failed_jobs',
                'failed_job_ids',
                'options',
                'cancelled_at',
                'created_at',
                'finished_at',
            ]],
            'failed jobs table' => ['failed_jobs', [
                'id',
                'uuid',
                'connection',
                'queue',
                'payload',
                'exception',
                'failed_at',
            ]],
            'admin audit logs table' => ['admin_audit_logs', [
                'id',
                'user_id',
                'action',
                'details',
                'created_at',
                'updated_at',
            ]],
            'movies table' => ['movies', [
                'id',
                'tmdb_id',
                'imdb_id',
                'dedup_hash',
                'omdb_id',
                'slug',
                'title',
                'original_title',
                'overview',
                'translation_metadata',
                'credits',
                'streaming_links',
                'trailers',
                'year',
                'runtime',
                'release_date',
                'plot',
                'tagline',
                'homepage',
                'budget',
                'revenue',
                'status',
                'popularity',
                'vote_average',
                'vote_count',
                'poster_path',
                'backdrop_path',
                'trailer_url',
                'media_type',
                'adult',
                'video',
                'title_search_vector',
                'overview_search_vector',
                'created_at',
                'updated_at',
                'deleted_at',
            ]],
            'people table' => ['people', [
                'id',
                'tmdb_id',
                'imdb_id',
                'slug',
                'name',
                'biography',
                'biography_translations',
                'birthday',
                'deathday',
                'place_of_birth',
                'gender',
                'known_for_department',
                'popularity',
                'profile_path',
                'poster_path',
                'created_at',
                'updated_at',
            ]],
            'tv shows table' => ['tv_shows', [
                'id',
                'tmdb_id',
                'imdb_id',
                'dedup_hash',
                'slug',
                'name',
                'original_name',
                'first_air_date',
                'last_air_date',
                'number_of_seasons',
                'number_of_episodes',
                'episode_run_time',
                'status',
                'overview',
                'tagline',
                'homepage',
                'popularity',
                'vote_average',
                'vote_count',
                'poster_path',
                'backdrop_path',
                'media_type',
                'adult',
                'created_at',
                'updated_at',
                'deleted_at',
            ]],
            'subscriptions table' => ['subscriptions', [
                'id',
                'user_id',
                'type',
                'stripe_id',
                'stripe_status',
                'stripe_price',
                'quantity',
                'trial_ends_at',
                'ends_at',
                'created_at',
                'updated_at',
            ]],
            'subscription items table' => ['subscription_items', [
                'id',
                'subscription_id',
                'stripe_id',
                'stripe_product',
                'stripe_price',
                'meter_id',
                'quantity',
                'meter_event_name',
                'created_at',
                'updated_at',
            ]],
            'reviews table' => ['reviews', [
                'id',
                'user_id',
                'movie_title',
                'rating',
                'body',
                'created_at',
                'updated_at',
            ]],
            'user watchlist table' => ['user_watchlist', [
                'id',
                'user_id',
                'watchlistable_type',
                'watchlistable_id',
                'created_at',
                'updated_at',
            ]],
            'movie language pivot table' => ['movie_language', [
                'id',
                'movie_id',
                'language_id',
                'created_at',
                'updated_at',
            ]],
            'movie country pivot table' => ['movie_country', [
                'id',
                'movie_id',
                'country_id',
                'created_at',
                'updated_at',
            ]],
            'parser entries table' => ['parser_entries', [
                'id',
                'subject_type',
                'subject_id',
                'parser',
                'payload',
                'baseline_snapshot',
                'status',
                'notes',
                'reviewed_by',
                'reviewed_at',
                'created_at',
                'updated_at',
            ]],
            'parser entry histories table' => ['parser_entry_histories', [
                'id',
                'parser_entry_id',
                'user_id',
                'action',
                'changes',
                'notes',
                'created_at',
                'updated_at',
            ]],
            'watch histories table' => ['watch_histories', [
                'id',
                'user_id',
                'watchable_type',
                'watchable_id',
                'watched_at',
                'created_at',
                'updated_at',
            ]],
            'ui translations table' => ['ui_translations', [
                'id',
                'group',
                'key',
                'value',
                'created_at',
                'updated_at',
            ]],
            'genres table' => ['genres', [
                'id',
                'tmdb_id',
                'slug',
                'name_translations',
                'created_at',
                'updated_at',
            ]],
            'movie genre pivot table' => ['movie_genre', [
                'id',
                'movie_id',
                'genre_id',
                'created_at',
                'updated_at',
            ]],
            'movie person pivot table' => ['movie_person', [
                'id',
                'movie_id',
                'person_id',
                'credit_type',
                'department',
                'character',
                'job',
                'credit_order',
                'created_at',
                'updated_at',
            ]],
            'tv show person pivot table' => ['tv_show_person', [
                'id',
                'tv_show_id',
                'person_id',
                'credit_type',
                'department',
                'character',
                'job',
                'credit_order',
                'created_at',
                'updated_at',
            ]],
            'user management logs table' => ['user_management_logs', [
                'id',
                'actor_id',
                'user_id',
                'action',
                'details',
                'created_at',
                'updated_at',
            ]],
        ];
    }
}
