<?php

return [
    'movies' => [
        [
            'tmdb_id' => 603692,
            'imdb_id' => 'tt9764362',
            'omdb_id' => 'omdb-tt9764362',
            'slug' => 'john-wick-chapter-4',
            'title' => 'John Wick: Chapter 4',
            'original_title' => 'John Wick: Chapter 4',
            'year' => 2023,
            'runtime' => 169,
            'release_date' => '2023-03-24',
            'overview' => [
                'en' => 'With the price on his head ever increasing, John Wick uncovers a path to defeating the High Table.',
            ],
            'tagline' => 'No way back. One way out.',
            'status' => 'released',
            'popularity' => 45.23,
            'vote_average' => 8.1,
            'vote_count' => 4800,
            'poster_path' => '/john-wick-4.jpg',
            'backdrop_path' => '/john-wick-4-backdrop.jpg',
            'media_type' => 'movie',
            'adult' => false,
            'video' => false,
        ],
        [
            'tmdb_id' => 19995,
            'imdb_id' => 'tt0499549',
            'omdb_id' => 'omdb-tt0499549',
            'slug' => 'avatar',
            'title' => 'Avatar',
            'original_title' => 'Avatar',
            'year' => 2009,
            'runtime' => 162,
            'release_date' => '2009-12-18',
            'overview' => [
                'en' => 'On the lush alien world of Pandora live the Na’vi, beings who appear primitive but are highly evolved.',
            ],
            'tagline' => 'Enter the world of Pandora.',
            'status' => 'released',
            'popularity' => 37.7,
            'vote_average' => 7.8,
            'vote_count' => 15000,
            'poster_path' => '/avatar.jpg',
            'backdrop_path' => '/avatar-backdrop.jpg',
            'media_type' => 'movie',
            'adult' => false,
            'video' => false,
        ],
    ],

    'tv_shows' => [
        [
            'tmdb_id' => 1399,
            'imdb_id' => 'tt0944947',
            'slug' => 'game-of-thrones',
            'name' => 'Game of Thrones',
            'original_name' => 'Game of Thrones',
            'first_air_date' => '2011-04-17',
            'last_air_date' => '2019-05-19',
            'number_of_seasons' => 8,
            'number_of_episodes' => 73,
            'episode_run_time' => 60,
            'status' => 'ended',
            'overview' => 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns.',
            'tagline' => 'Winter is coming.',
            'homepage' => 'https://www.hbo.com/game-of-thrones',
            'popularity' => 98.4,
            'vote_average' => 8.4,
            'vote_count' => 17000,
            'poster_path' => '/game-of-thrones.jpg',
            'backdrop_path' => '/game-of-thrones-backdrop.jpg',
            'media_type' => 'tv',
            'adult' => false,
        ],
        [
            'tmdb_id' => 456,
            'imdb_id' => 'tt0903747',
            'slug' => 'breaking-bad',
            'name' => 'Breaking Bad',
            'original_name' => 'Breaking Bad',
            'first_air_date' => '2008-01-20',
            'last_air_date' => '2013-09-29',
            'number_of_seasons' => 5,
            'number_of_episodes' => 62,
            'episode_run_time' => 47,
            'status' => 'ended',
            'overview' => 'A chemistry teacher diagnosed with cancer turns to a life of crime to secure his family\'s future.',
            'tagline' => 'Change the equation.',
            'homepage' => 'https://www.amc.com/shows/breaking-bad',
            'popularity' => 85.1,
            'vote_average' => 8.6,
            'vote_count' => 16000,
            'poster_path' => '/breaking-bad.jpg',
            'backdrop_path' => '/breaking-bad-backdrop.jpg',
            'media_type' => 'tv',
            'adult' => false,
        ],
    ],

    'people' => [
        [
            'tmdb_id' => 6384,
            'imdb_id' => 'nm0634240',
            'slug' => 'keanu-reeves',
            'name' => 'Keanu Reeves',
            'biography' => 'Keanu Charles Reeves is a Canadian actor known for The Matrix and John Wick franchises.',
            'birthday' => '1964-09-02',
            'place_of_birth' => 'Beirut, Lebanon',
            'gender' => 2,
            'known_for_department' => 'Acting',
            'popularity' => 90.125,
            'profile_path' => '/keanu-reeves.jpg',
        ],
        [
            'tmdb_id' => 192,
            'imdb_id' => 'nm0000138',
            'slug' => 'sigourney-weaver',
            'name' => 'Sigourney Weaver',
            'biography' => 'Susan Alexandra "Sigourney" Weaver is an American actress with a prolific career in film and theater.',
            'birthday' => '1949-10-08',
            'place_of_birth' => 'New York City, USA',
            'gender' => 1,
            'known_for_department' => 'Acting',
            'popularity' => 72.431,
            'profile_path' => '/sigourney-weaver.jpg',
        ],
    ],
];
