name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            export APP_DIR=${{ secrets.PROD_APP_DIR }}
            cd "$APP_DIR"
            git pull origin main
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            bash scripts/deploy-production.sh
